///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace CaltermTest_SandBox
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the CaltermTest_SandBoxRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("8d75dddd-bbae-48fd-a725-a61287b34cc2")]
    public partial class CaltermTest_SandBoxRepository : RepoGenBaseFolder
    {
        static CaltermTest_SandBoxRepository instance = new CaltermTest_SandBoxRepository();
        CaltermTest_SandBoxRepositoryFolders.ModuleSelectionAppFolder _moduleselection;
        CaltermTest_SandBoxRepositoryFolders.ManualConnectAppFolder _manualconnect;
        CaltermTest_SandBoxRepositoryFolders.MsgBoxAppFolder _msgbox;
        CaltermTest_SandBoxRepositoryFolders.ApplicationFormAppFolder _applicationform;
        CaltermTest_SandBoxRepositoryFolders.OpenAppFolder _open;

        /// <summary>
        /// Gets the singleton class instance representing the CaltermTest_SandBoxRepository element repository.
        /// </summary>
        [RepositoryFolder("8d75dddd-bbae-48fd-a725-a61287b34cc2")]
        public static CaltermTest_SandBoxRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public CaltermTest_SandBoxRepository() 
            : base("CaltermTest_SandBoxRepository", "/", null, 0, false, "8d75dddd-bbae-48fd-a725-a61287b34cc2", ".\\RepositoryImages\\CaltermTest_SandBoxRepository8d75dddd.rximgres")
        {
            _moduleselection = new CaltermTest_SandBoxRepositoryFolders.ModuleSelectionAppFolder(this);
            _manualconnect = new CaltermTest_SandBoxRepositoryFolders.ManualConnectAppFolder(this);
            _msgbox = new CaltermTest_SandBoxRepositoryFolders.MsgBoxAppFolder(this);
            _applicationform = new CaltermTest_SandBoxRepositoryFolders.ApplicationFormAppFolder(this);
            _open = new CaltermTest_SandBoxRepositoryFolders.OpenAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("8d75dddd-bbae-48fd-a725-a61287b34cc2")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ModuleSelection folder.
        /// </summary>
        [RepositoryFolder("d2ea8359-b9fd-446c-9777-62e9cbab1f36")]
        public virtual CaltermTest_SandBoxRepositoryFolders.ModuleSelectionAppFolder ModuleSelection
        {
            get { return _moduleselection; }
        }

        /// <summary>
        /// The ManualConnect folder.
        /// </summary>
        [RepositoryFolder("3fc52fe8-2043-44d8-b39a-5d913947e6d7")]
        public virtual CaltermTest_SandBoxRepositoryFolders.ManualConnectAppFolder ManualConnect
        {
            get { return _manualconnect; }
        }

        /// <summary>
        /// The MsgBox folder.
        /// </summary>
        [RepositoryFolder("bf5be973-be0c-4d57-8764-d898efcdd467")]
        public virtual CaltermTest_SandBoxRepositoryFolders.MsgBoxAppFolder MsgBox
        {
            get { return _msgbox; }
        }

        /// <summary>
        /// The ApplicationForm folder.
        /// </summary>
        [RepositoryFolder("c68f64ec-fbed-4af6-9673-938139fadff4")]
        public virtual CaltermTest_SandBoxRepositoryFolders.ApplicationFormAppFolder ApplicationForm
        {
            get { return _applicationform; }
        }

        /// <summary>
        /// The Open folder.
        /// </summary>
        [RepositoryFolder("63eaf653-3f9a-4e46-873a-0930471074ff")]
        public virtual CaltermTest_SandBoxRepositoryFolders.OpenAppFolder Open
        {
            get { return _open; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class CaltermTest_SandBoxRepositoryFolders
    {
        /// <summary>
        /// The ModuleSelectionAppFolder folder.
        /// </summary>
        [RepositoryFolder("d2ea8359-b9fd-446c-9777-62e9cbab1f36")]
        public partial class ModuleSelectionAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _manualInfo;
            RepoItemInfo _buttoncancelInfo;
            RepoItemInfo _configfilerow0Info;

            /// <summary>
            /// Creates a new ModuleSelection  folder.
            /// </summary>
            public ModuleSelectionAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ModuleSelection", "/form[@controlname='ModuleSelection']", parentFolder, 30000, null, true, "d2ea8359-b9fd-446c-9777-62e9cbab1f36", "")
            {
                _manualInfo = new RepoItemInfo(this, "Manual", "button[@controlname='manual']", 30000, null, "3ccfe7df-ac2d-453b-a595-3f1368922c7f");
                _buttoncancelInfo = new RepoItemInfo(this, "ButtonCancel", "button[@controlname='ButtonCancel']", 30000, null, "2cd320e4-0ca4-4abb-9b53-4f164c6ec9d1");
                _configfilerow0Info = new RepoItemInfo(this, "ConfigFileRow0", "tabpagelist[@controlname='productTabControl']/tabpage[@controlname='productsTabPage']//table[@controlname='configFileDataGridView']/?/?/cell[@accessiblename='Config File Row 0']", 30000, null, "31480983-f32f-4d11-a031-b9b19bbc99dc");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("d2ea8359-b9fd-446c-9777-62e9cbab1f36")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("d2ea8359-b9fd-446c-9777-62e9cbab1f36")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Manual item.
            /// </summary>
            [RepositoryItem("3ccfe7df-ac2d-453b-a595-3f1368922c7f")]
            public virtual Ranorex.Button Manual
            {
                get
                {
                    return _manualInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Manual item info.
            /// </summary>
            [RepositoryItemInfo("3ccfe7df-ac2d-453b-a595-3f1368922c7f")]
            public virtual RepoItemInfo ManualInfo
            {
                get
                {
                    return _manualInfo;
                }
            }

            /// <summary>
            /// The ButtonCancel item.
            /// </summary>
            [RepositoryItem("2cd320e4-0ca4-4abb-9b53-4f164c6ec9d1")]
            public virtual Ranorex.Button ButtonCancel
            {
                get
                {
                    return _buttoncancelInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonCancel item info.
            /// </summary>
            [RepositoryItemInfo("2cd320e4-0ca4-4abb-9b53-4f164c6ec9d1")]
            public virtual RepoItemInfo ButtonCancelInfo
            {
                get
                {
                    return _buttoncancelInfo;
                }
            }

            /// <summary>
            /// The ConfigFileRow0 item.
            /// </summary>
            [RepositoryItem("31480983-f32f-4d11-a031-b9b19bbc99dc")]
            public virtual Ranorex.Cell ConfigFileRow0
            {
                get
                {
                    return _configfilerow0Info.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The ConfigFileRow0 item info.
            /// </summary>
            [RepositoryItemInfo("31480983-f32f-4d11-a031-b9b19bbc99dc")]
            public virtual RepoItemInfo ConfigFileRow0Info
            {
                get
                {
                    return _configfilerow0Info;
                }
            }
        }

        /// <summary>
        /// The ManualConnectAppFolder folder.
        /// </summary>
        [RepositoryFolder("3fc52fe8-2043-44d8-b39a-5d913947e6d7")]
        public partial class ManualConnectAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _browseforconfigfileInfo;
            RepoItemInfo _buttonokInfo;
            RepoItemInfo _cancelInfo;

            /// <summary>
            /// Creates a new ManualConnect  folder.
            /// </summary>
            public ManualConnectAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ManualConnect", "/form[@controlname='ManualConnect']", parentFolder, 30000, null, true, "3fc52fe8-2043-44d8-b39a-5d913947e6d7", "")
            {
                _browseforconfigfileInfo = new RepoItemInfo(this, "BrowseForConfigFile", "?/?/button[@controlname='browseForConfigFile']", 30000, null, "3fccc5aa-f9ec-4967-9594-03365a3a2b9a");
                _buttonokInfo = new RepoItemInfo(this, "ButtonOk", "?/?/button[@controlname='ok']", 30000, null, "5c9711ab-f793-4fc8-9047-4da12dcad4f5");
                _cancelInfo = new RepoItemInfo(this, "Cancel", "?/?/button[@controlname='cancel']", 30000, null, "2bbb0e3d-bca1-4c7b-b95d-3b998844e58e");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("3fc52fe8-2043-44d8-b39a-5d913947e6d7")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("3fc52fe8-2043-44d8-b39a-5d913947e6d7")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The BrowseForConfigFile item.
            /// </summary>
            [RepositoryItem("3fccc5aa-f9ec-4967-9594-03365a3a2b9a")]
            public virtual Ranorex.Button BrowseForConfigFile
            {
                get
                {
                    return _browseforconfigfileInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The BrowseForConfigFile item info.
            /// </summary>
            [RepositoryItemInfo("3fccc5aa-f9ec-4967-9594-03365a3a2b9a")]
            public virtual RepoItemInfo BrowseForConfigFileInfo
            {
                get
                {
                    return _browseforconfigfileInfo;
                }
            }

            /// <summary>
            /// The ButtonOk item.
            /// </summary>
            [RepositoryItem("5c9711ab-f793-4fc8-9047-4da12dcad4f5")]
            public virtual Ranorex.Button ButtonOk
            {
                get
                {
                    return _buttonokInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonOk item info.
            /// </summary>
            [RepositoryItemInfo("5c9711ab-f793-4fc8-9047-4da12dcad4f5")]
            public virtual RepoItemInfo ButtonOkInfo
            {
                get
                {
                    return _buttonokInfo;
                }
            }

            /// <summary>
            /// The Cancel item.
            /// </summary>
            [RepositoryItem("2bbb0e3d-bca1-4c7b-b95d-3b998844e58e")]
            public virtual Ranorex.Button Cancel
            {
                get
                {
                    return _cancelInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Cancel item info.
            /// </summary>
            [RepositoryItemInfo("2bbb0e3d-bca1-4c7b-b95d-3b998844e58e")]
            public virtual RepoItemInfo CancelInfo
            {
                get
                {
                    return _cancelInfo;
                }
            }
        }

        /// <summary>
        /// The MsgBoxAppFolder folder.
        /// </summary>
        [RepositoryFolder("bf5be973-be0c-4d57-8764-d898efcdd467")]
        public partial class MsgBoxAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _closeInfo;

            /// <summary>
            /// Creates a new MsgBox  folder.
            /// </summary>
            public MsgBoxAppFolder(RepoGenBaseFolder parentFolder) :
                    base("MsgBox", "/form[@controlname='MsgBox']", parentFolder, 30000, null, true, "bf5be973-be0c-4d57-8764-d898efcdd467", "")
            {
                _closeInfo = new RepoItemInfo(this, "Close", "?/?/button[@accessiblename='Close']", 30000, null, "3d540c60-6569-47ab-ad05-4ac24d93d08c");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("bf5be973-be0c-4d57-8764-d898efcdd467")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("bf5be973-be0c-4d57-8764-d898efcdd467")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Close item.
            /// </summary>
            [RepositoryItem("3d540c60-6569-47ab-ad05-4ac24d93d08c")]
            public virtual Ranorex.Button Close
            {
                get
                {
                    return _closeInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Close item info.
            /// </summary>
            [RepositoryItemInfo("3d540c60-6569-47ab-ad05-4ac24d93d08c")]
            public virtual RepoItemInfo CloseInfo
            {
                get
                {
                    return _closeInfo;
                }
            }
        }

        /// <summary>
        /// The ApplicationFormAppFolder folder.
        /// </summary>
        [RepositoryFolder("c68f64ec-fbed-4af6-9673-938139fadff4")]
        public partial class ApplicationFormAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _closeInfo;

            /// <summary>
            /// Creates a new ApplicationForm  folder.
            /// </summary>
            public ApplicationFormAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationForm", "/form[@controlname='ApplicationForm']", parentFolder, 30000, null, true, "c68f64ec-fbed-4af6-9673-938139fadff4", "")
            {
                _closeInfo = new RepoItemInfo(this, "Close", "?/?/button[@accessiblename='Close']", 30000, null, "e890c5c5-49e4-4411-8959-1972ec979b7a");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("c68f64ec-fbed-4af6-9673-938139fadff4")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("c68f64ec-fbed-4af6-9673-938139fadff4")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Close item.
            /// </summary>
            [RepositoryItem("e890c5c5-49e4-4411-8959-1972ec979b7a")]
            public virtual Ranorex.Button Close
            {
                get
                {
                    return _closeInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Close item info.
            /// </summary>
            [RepositoryItemInfo("e890c5c5-49e4-4411-8959-1972ec979b7a")]
            public virtual RepoItemInfo CloseInfo
            {
                get
                {
                    return _closeInfo;
                }
            }
        }

        /// <summary>
        /// The OpenAppFolder folder.
        /// </summary>
        [RepositoryFolder("63eaf653-3f9a-4e46-873a-0930471074ff")]
        public partial class OpenAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _systemitemnamedisplayInfo;
            RepoItemInfo _buttonopenInfo;

            /// <summary>
            /// Creates a new Open  folder.
            /// </summary>
            public OpenAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Open", "/form[@title='Open']", parentFolder, 30000, null, true, "63eaf653-3f9a-4e46-873a-0930471074ff", "")
            {
                _systemitemnamedisplayInfo = new RepoItemInfo(this, "SystemItemNameDisplay", "element[@class='DUIViewWndClassName']//container[@caption='ShellView']/?/?/listitem[@automationid='0']/text[@automationid='System.ItemNameDisplay']", 30000, null, "889b0642-273f-4de8-abf1-7d1de52a785c");
                _buttonopenInfo = new RepoItemInfo(this, "ButtonOpen", "button[@text='&Open']", 30000, null, "1e44aeda-9e35-486d-9954-2ac295555d49");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("63eaf653-3f9a-4e46-873a-0930471074ff")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("63eaf653-3f9a-4e46-873a-0930471074ff")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The SystemItemNameDisplay item.
            /// </summary>
            [RepositoryItem("889b0642-273f-4de8-abf1-7d1de52a785c")]
            public virtual Ranorex.Text SystemItemNameDisplay
            {
                get
                {
                    return _systemitemnamedisplayInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The SystemItemNameDisplay item info.
            /// </summary>
            [RepositoryItemInfo("889b0642-273f-4de8-abf1-7d1de52a785c")]
            public virtual RepoItemInfo SystemItemNameDisplayInfo
            {
                get
                {
                    return _systemitemnamedisplayInfo;
                }
            }

            /// <summary>
            /// The ButtonOpen item.
            /// </summary>
            [RepositoryItem("1e44aeda-9e35-486d-9954-2ac295555d49")]
            public virtual Ranorex.Button ButtonOpen
            {
                get
                {
                    return _buttonopenInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonOpen item info.
            /// </summary>
            [RepositoryItemInfo("1e44aeda-9e35-486d-9954-2ac295555d49")]
            public virtual RepoItemInfo ButtonOpenInfo
            {
                get
                {
                    return _buttonopenInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
